import{a as v,S,i as s}from"./assets/vendor-Cx9ob2aQ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const m of n.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&f(m)}).observe(document,{childList:!0,subtree:!0});function e(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function f(t){if(t.ep)return;t.ep=!0;const n=e(t);fetch(t.href,n)}})();const B="https://pixabay.com/api/",R="53390441-690cb9fa742523782d54564fc",A={key:R,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function p(o,r=1){try{const e={...A,q:o,page:r};return(await v.get(B,{params:e})).data}catch(e){throw e}}const l=document.getElementById("gallery"),c=document.querySelector(".loader"),g=new S(".gallery a",{captionsData:"alt",captionDelay:250}),d=document.getElementById("load-more");function L(o){if(!Array.isArray(o)||o.length===0)return;const r=o.map(e=>`
    <li class="gallery__item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${e.likes}</p>
          <p class="info-item"><b>Views:</b> ${e.views}</p>
          <p class="info-item"><b>Comments:</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>
    </li>`).join("");l.insertAdjacentHTML("beforeend",r),g.refresh()}function I(){l&&(l.innerHTML="",g.refresh())}function b(){c&&c.classList.remove("is-hidden")}function w(){c&&c.classList.add("is-hidden")}function y(){d&&d.classList.remove("is-hidden")}function u(){d&&d.classList.add("is-hidden")}function P(){return l}const M=document.querySelector(".form"),_=document.querySelector('input[name="search-text"]'),$=document.getElementById("load-more");let h="",a=1,i=0;const E=15;M.addEventListener("submit",q);$.addEventListener("click",O);async function q(o){o.preventDefault();const r=_.value.trim();if(!r){s.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}h=r,a=1,i=0,I(),u(),b();try{const e=await p(h,a);if(!e||!e.hits.length){s.info({title:"Info",message:"Sorry, there are no images matching your search query!",position:"topRight"});return}i=e.totalHits,L(e.hits),s.success({title:"Success",message:`Hooray! We found ${i} images.`,position:"topRight"}),i<=E?(u(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):y()}catch(e){console.error(e),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}}async function O(){a+=1,u(),b();try{const o=await p(h,a);L(o.hits),x(),a*E>=i?(u(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):y()}catch(o){console.error(o),y()}finally{w()}}function x(){const r=P().querySelector(".gallery__item");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
